(ns app.core)

;; ISO 639.2 language codes
;; Issues:
;; - Klingon (plqaD)
(def langs {:en "english"
             :ar "arabic"
             :bg "bulgarian"
             :ca "catalan"
             :cs "czech"
             :da "danish"
             :nl "dutch"
             :et "estonian"
             :fi "finnish"
             :fr "french"
             :de "german"
             :el "greek"
             :hr "hebrew"
             :hi "hindi"
             :hm "hmong daw"
             :hu "hungarian"
             :id "indonesian"
             :it "italian"
             :ja "japanese"
             :hu "hungarian"
             :ko "korean"
             :lv "latvian"
             :lt "lithuanian"
             :ms "malay"
             :mt "maltese"
             :nn "norwegian"
             :fa "persian"
             :pl "polish"
             :pt "portuguese"
             :ro "romanian"
             :ru "russian"
             :hu "hungarian"
             :sk "slovak"
             :sl "slovenian"
             :sk "slovak"
             :es "spanish"
             :sv "swedish"
             :th "thai"
             :tr "turkish"
             :uk "ukrainian"
             :ur "urdu"
             :vi "vietnamese"
             :cy "welsh"
             :zh_CN "chinese simplified"
             :zh_TW "chinese traditional"
             :ht "haitian creole"
             :tlh "klingon"})
